language: ruby
rvm:
- 2.4.0
branches:
  only:
  - master
before_script:
- chmod +x deploy/deploy.sh
script: "./deploy/deploy.sh"
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_906a04090fcb_key -iv $encrypted_906a04090fcb_iv -in deploy/shunk031_github_io_key.enc -out /tmp/deploy_key -d
notifications:
  slack:
    secure: XrHkul6TKGFsa7gGWTOydrQ2HqVKth2Ap41w5WUunPmRG/ndb/AjIAowMTAhAwHiWoJAavDRrK4wJdfjzlVKXg0STFzeaWJW/zniv8+VWY9L4sPEX4XY0MazLssad8oqndZaCEhj56n8Nfkj6wOCrquidg6C3jxOe4GhMdTzPj7wknqFlV3ebv6qhKBJIwi95PFrmMrn4H6ZE6uX0RivOlMP76pFYCBLRb6eTNJh4Qh03LKJnPFWx4F1+462P/upopAcwcGeQQBGu+YbC9JIucnSbVq9IhptRqTzH3Z3NCv2Bapj4bpFxeOtyaUuS/QfKd1AolhkJXT0CeqI0nmfwFW5j/CibgIq8/4vcpxJrxf0raF2zy3w0euwEyICOhpeJivz6+hsV4Y90DKITfxfRjLgQ6RcSpUKRweJ01j5gslnR1jdhuN5qb0XGCsuReYyAPkAA2Y95AbjlZ3FGOSoqYjhEleRjo8Y/eKdqyUILcQqGZ3ybOjXi9R+2s9HxGMaw2Hh4JSs1RYqF/Y/pqMqLAdiGpZcB4cgnecOgZeoTw4vCA6wypC6UGjHTfrYyc5T/D6BSh0m59xwZwEun1ulTV1geB2fY3R+CsyhY8drpaLh5LkuC67a2nt8VIljx1n/aIHMVzZlb2PyA9rolqwolEvk1LnMDJrYdgSFU5VJhlA=
