language: ruby

rvm:
- 2.4.0

branches:
  only:
  - master

before_script:
- chmod +x deploy/deploy.sh

script: "./deploy/deploy.sh"

sudo: false

before_install:
- openssl aes-256-cbc -K $encrypted_906a04090fcb_key -iv $encrypted_906a04090fcb_iv -in deploy/shunk031_github_io_key.enc -out /tmp/deploy_key -d
