name: Page Build

on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo

      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        env:
          MUFFET_TIMEOUT: 20
          MUFFET_MAX_CONNECTIONS: 10
        with:
          url: https://${{ github.event.repository.name }}
          pages_path: ./public
          cmd_params: "\
            -t 20 \
            -c 10 \
            -e linkedin.com \
            -e twitter.com \
            -e facebook.com \
            -e gstatic.com \
            -e researchgate.net \
            -e arxiv.org \
            -e valuenex.com \
            -e paper-survey \
            -e publication/#\\d"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/source'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: master # deploying branch
          cname: shunk031.me
