name: Page Build

on:
  push:
    branches:
      - source # default branch

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo

      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v1
        with:
          url: https://${{ github.event.repository.name }}
          pages_path: ./public
          cmd_params: "\
            --timeout=20 \
            --max-connections=10 \
            -e linkedin.com \
            -e twitter.com \
            -e facebook.com \
            -e gstatic.com \
            -e researchgate.net \
            -e arxiv.org \
            -e publication/#\\d"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: master # deploying branch
          cname: shunk031.me
